### ISSUE TITLE
"ErrorPayload" when have to show my error in the ErrorComponent

### ISSUE THREAD

**Issue by kvandake** [kenneth1003/react-render-ctrl#2]
I have a specific case.
I have to should show the error from my api but i dont understand how to do it.

```ts
export default withRenderCtrl(ProjectList, {
    ErrorComponent: () => <ErrorComponent error={ (?props?)errorPayload}/>
}
```

* errorPayload - instance of Error.

**Comment by kenneth1003** [comment]
Seems like we need an additional props: `errorPayload`.
something like:
```
<YourComponent
    isError={ something.went.wrong }
    errorPayload={ some.error.payload }    // optional props
    isLoading={ api.isFetching }
    isDataReady={ data.length > 0 && data[0].value }
/>
```
I will enhance it in a couple of days when I have time.
Thanks for letting me know!

**Comment by kenneth1003** [comment]
I just add a new version with props control of the customized components. Hope it works.
