### ISSUE TITLE
Will the library support Typescript definition?

### ISSUE THREAD

**Issue by kvandake** [kenneth1003/react-render-ctrl#3]

**Comment by kenneth1003** [comment]
I am busy recently. Typing support might added in the future.
Feel free to create a PR, if you are in a hurry.
Thanks!

**Comment by kenneth1003** [comment]
@kvandake 
It's been a while, butI have published a new version on npm to add basic type file.
https://www.npmjs.com/package/react-render-ctrl
Thanks for reporting 👍
