### ISSUE TITLE
Console warning for RenderCtrlProvider component

### ISSUE THREAD

**Issue by rishika-reddy-p** [kenneth1003/react-render-ctrl#4]
![Screenshot from 2020-11-10 18-27-20](https://user-images.githubusercontent.com/38957786/98677223-bd162d80-2382-11eb-9a58-63f6132e9663.png)

Hi, will it be possible to fix this console warning that is caused by RenderCtrlProvider and RenderCtrl components

The reason why this needs to be fixed is: https://reactjs.org/docs/context.html#legacy-api

Thanks!

**Comment by kenneth1003** [comment]
Thanks for the report!
I will fix it when I have time 🙏

**Comment by rishika-reddy-p** [comment]
Thank you for your reply. By the way, great library!

**Comment by kenneth1003** [comment]
@rishika-reddy-p I have published a new version on npm to resolve this issue
https://www.npmjs.com/package/react-render-ctrl
Thanks for reporting 👍
