### ISSUE TITLE
Changing State inside Wrapped Component

### ISSUE THREAD

**Issue by shivamkj** [kenneth1003/react-render-ctrl#8]
I could not figure out how to modify loading, error states inside the wrapped component. Could you add complete app example on implementing your library.

**Comment by kenneth1003** [comment]
Thanks! I also find out some dependency issues with `prop-types`.
I will fix it in the later version

**Comment by kenneth1003** [comment]
Hi @shivamkj , I just created a few demos, you can refer to https://codesandbox.io/s/react-render-ctrl-demo-0zomg?file=/src/MinimalUseCase/BigNumber.js

I will update README in the next version, thanks again for the feedback!
